# Generated by Django 5.2.1 on 2025-05-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='office',
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', editable=False, help_text='Auto-generated from first and last name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeeactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Employee Created'), ('UPDATED', 'Employee Updated'), ('STATUS_CHANGED', 'Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('MANAGER_CHANGED', 'Manager Changed'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('ORG_CHART_VISIBILITY_CHANGED', 'Org Chart Visibility Changed'), ('OTHER', 'Other Activity')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
