# Generated by Django 5.2.1 on 2025-07-15 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_contracttypeconfig_contract_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Employee Document', 'verbose_name_plural': 'Employee Documents'},
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_path',
        ),
       
        migrations.AddField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload document file', null=True, upload_to='employee_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
       
      
        migrations.AddField(
            model_name='employeedocument',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('ID', 'ID Document'), ('CERTIFICATE', 'Certificate'), ('CV', 'Curriculum Vitae'), ('PERFORMANCE', 'Performance Review'), ('MEDICAL', 'Medical Certificate'), ('TRAINING', 'Training Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='name',
            field=models.CharField(help_text='Document name or title', max_length=255),
        ),
        migrations.CreateModel(
            name='FileUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('upload_type', models.CharField(choices=[('PROFILE_IMAGE', 'Profile Image'), ('DOCUMENT', 'Document')], max_length=20)),
                ('total_files', models.PositiveIntegerField(default=1)),
                ('uploaded_files', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='api.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
