# Generated by Django 5.2.1 on 2025-07-15 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_employeedocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='description',
            field=models.TextField(blank=True, help_text='Document description'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Current status of the document', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Document expiry date', null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Mark as confidential'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
