# Generated by Django 5.2.1 on 2025-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_employeedocument_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_status',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='notify_before_expiry_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to send notification'),
        ),
    ]
