# Generated by Django 5.2.1 on 2025-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_employeedocument_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='document_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Current status of the document', max_length=20),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Is this document required for employee?'),
        ),
    ]
