# Generated by Django 5.2.1 on 2025-07-15 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_employeedocument_document_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='is_current_version',
            field=models.BooleanField(default=True, help_text='Is this the current version?'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='Document that replaces this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='api.employeedocument'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Document version number'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_version', True), ('is_deleted', False)), fields=('employee', 'name', 'document_type'), name='unique_current_version_per_employee_document'),
        ),
    ]
