# Generated by Django 5.2.1 on 2025-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_employeedocument_is_current_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='employeedocument',
            name='unique_current_version_per_employee_document',
        ),
    ]
