# Generated by Django 5.2.1 on 2026-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_assettransferrequest_employee_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractrenewalrequest',
            name='new_contract_duration_months',
        ),
        migrations.AlterField(
            model_name='timeoffsettings',
            name='hr_notification_emails',
            field=models.TextField(default='n.orujova@almettrading.com', help_text='HR email-ləri (vergüllə ayrılmış)'),
        ),
    ]
