# Generated by Django 5.2.1 on 2026-01-30 11:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_remove_contractrenewalrequest_new_contract_duration_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company name (e.g., 'Almet HR', 'Almet IT')", max_length=200, unique=True)),
                ('code', models.CharField(help_text="Company code (e.g., 'HR', 'IT')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏢', max_length=10)),
                ('color', models.CharField(default='bg-gradient-to-br from-blue-500 to-blue-600', help_text='Tailwind gradient class', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_function', models.OneToOneField(blank=True, help_text='Link to business function if exists', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_company', to='api.businessfunction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Company',
                'verbose_name_plural': 'Document Companies',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.documentcompany')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Folder',
                'verbose_name_plural': 'Document Folders',
                'ordering': ['company', 'order', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('procedure', 'Procedure'), ('guideline', 'Guideline'), ('manual', 'Manual'), ('template', 'Template'), ('form', 'Form'), ('reference', 'Reference'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'pptx', 'txt', 'doc', 'xls', 'ppt'])])),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.documentfolder')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['folder', 'document_type', 'is_active'], name='api_documen_folder__beb83a_idx'), models.Index(fields=['document_type', 'is_active'], name='api_documen_documen_e9a6fb_idx'), models.Index(fields=['-updated_at'], name='api_documen_updated_44aa93_idx')],
            },
        ),
    ]
