# Generated by Django 5.2.1 on 2026-01-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_documentcompany_documentfolder_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcompany',
            name='color',
        ),
        migrations.RemoveField(
            model_name='documentcompany',
            name='description',
        ),
    ]
