# Generated by Django 5.2.1 on 2026-01-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_remove_documentcompany_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
    ]
