# Generated by Django 5.2.1 on 2026-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_remove_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstriprequest',
            name='initial_finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial amount suggested by employee', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='content',
            field=models.TextField(blank=True, help_text='Full news content (supports rich text)'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief summary (shown in list view)', max_length=500),
        ),
    ]
