# Generated by Django 5.2.1 on 2026-02-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_businesstriprequest_initial_finance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract_extensions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_extension_date',
        ),
    ]
