# Generated by Django 5.2.1 on 2026-02-06 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_remove_employee_contract_extensions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('training_title', models.CharField(max_length=300)),
                ('purpose_justification', models.TextField(help_text='Explain why this training is needed')),
                ('training_provider', models.CharField(blank=True, help_text='Training provider/organization (if known)', max_length=200)),
                ('preferred_dates_start', models.DateField(blank=True, help_text='Preferred start date', null=True)),
                ('preferred_dates_end', models.DateField(blank=True, help_text='Preferred end date', null=True)),
                ('duration', models.CharField(help_text="e.g., '3 days', '2 weeks', '1 month'", max_length=100)),
                ('location', models.CharField(help_text='Training location (city, online, etc.)', max_length=200)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost in currency', max_digits=10)),
                ('learning_objectives', models.TextField(help_text='What will participants learn?')),
                ('expected_benefits', models.TextField(help_text='How will this training benefit the organization?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('manager_comments', models.TextField(blank=True, help_text="Manager's comments on the request")),
                ('approved_rejected_date', models.DateTimeField(blank=True, help_text='Date when manager approved/rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Request',
                'verbose_name_plural': 'Training Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Request Participant',
                'verbose_name_plural': 'Training Request Participants',
            },
        ),
        migrations.AlterField(
            model_name='businesstriprequest',
            name='request_id',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['request_id', 'is_deleted'], name='business_tr_request_e2cc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['status', 'is_deleted'], name='business_tr_status_709834_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['employee', 'is_deleted'], name='business_tr_employe_8a4fba_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['requester', 'is_deleted'], name='business_tr_request_602afe_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstriprequest',
            index=models.Index(fields=['created_at', 'is_deleted'], name='business_tr_created_bc5ba4_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesstriprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('request_id',), name='unique_active_request_id'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='manager',
            field=models.ForeignKey(help_text='Manager who will approve this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_to_approve', to='api.employee'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_made', to='api.employee'),
        ),
        migrations.AddField(
            model_name='trainingrequestparticipant',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrequestparticipant',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrequestparticipant',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AddField(
            model_name='trainingrequestparticipant',
            name='training_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.trainingrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrequestparticipant',
            unique_together={('training_request', 'employee')},
        ),
    ]
