# Generated by Django 5.2.1 on 2026-02-06 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_trainingrequest_trainingrequestparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected (manager or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_training_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='approved_rejected_date',
            field=models.DateTimeField(blank=True, help_text='Date when manager/admin approved/rejected', null=True),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager who will approve this request (line_manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_to_approve', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
